var React = require('react');
var Article = require('./Article.jsx');

var ArticleManager = React.createClass({

    render: function(){

        // "articles" is an array of objects.
        //
        // Ideally, this would receive & parse a JSON using an ajax request or something
        // similar, but for the sake of simplicity, everything will be static.
        //
        // The "articles" object could easily be passed in as a property, as well.
        //
        // Naturally, these were pulled from The Onion.

        var articles = [
            {
                title: "Ted Cruz Opens Up To Town Hall Audience About Early Days As Larva Feeding On Porcupine Carcass",
                subtitle: "NEWS IN BRIEF",
                date: "March 29, 2016",
                volume: "52",
                issue: "12",
                tags: "Politics · Politicians · Election 2016 · Ted Cruz",
                text: "MILWAUKEE—Attempting to connect with voters in the run-up to Wisconsin’s crucial state primary next week, Republican presidential candidate Ted Cruz reportedly opened up to a town hall crowd Tuesday about his early days as a larva feeding on a rotting porcupine carcass. “Those days spent regurgitating my own bile in order to soften up the animal’s decomposing flesh taught me a lot about life and really shaped who I am today,” said a wistful Cruz, adding that he learned to appreciate hard work and family while burrowing alongside the hundreds of other members of his brood into the most festering part of the carrion.",
                image: "http://i.onionstatic.com/onion/5307/0/16x9/800.jpg",
                url: "http://www.theonion.com/article/ted-cruz-opens-town-hall-audience-about-early-days-52657",
                avatar: "http://assets.onionstatic.com/onion/static/images/onion_logo.png"
            },
            {
                title: "Advisors Tell Trump, Cruz To Stick To Just Attacking All Women In General",
                subtitle: "NEWS IN BRIEF",
                date: "March 28, 2016",
                volume: "52",
                issue: "12",
                tags: "Politics · Politicians · Election 2016 · Donald Trump · Ted Cruz",
                text: "JANESVILLE, WI—Attempting to reduce the negative publicity generated by their candidates’ recent attacks on each other’s wives, top campaign advisors reportedly instructed Republican presidential hopefuls Donald Trump and Ted Cruz in private meetings Monday to stick to just attacking all women in general, sources confirmed. “Using derogatory language and treating women as mere objects is fine, just as long as you make sure you’re making a blanket statement about the entire female population and not a specific candidate’s wife, okay?” said Cruz’s senior communications advisor, Jason Miller, repeating nearly verbatim the advice Trump’s aides reportedly gave the GOP frontrunner earlier in the day during a strategy session.",
                image: "http://i.onionstatic.com/onion/5305/7/16x9/800.jpg",
                url: "http://www.theonion.com/article/advisors-tell-trump-cruz-stick-just-attacking-all--52647",
                avatar: "http://assets.onionstatic.com/onion/static/images/onion_logo.png"
            },
            {
                title: "Hillary Clinton Pleasantly Surprised After Finding Old $20,000 Donation Check In Coat Pocket",
                subtitle: "NEWS IN BRIEF",
                date: "March 18, 2016",
                volume: "52",
                issue: "10",
                tags: "Politics · Politicians · Hillary Clinton · Election 2016",
                text: "NEW YORK—Smiling at her good fortune following the unexpected discovery, Democratic presidential candidate Hillary Clinton was reportedly pleasantly surprised Friday upon finding an old $20,000 donation check in her coat pocket. “I was just headed out the door and was digging around for my keys, and I just happened to find a 20-grand check I had completely forgotten about crumpled up in there,” said Clinton, who noted the $20,000 contribution was stuffed way at the bottom of her pocket, and speculated that it had probably been down there for about eight years.",
                image: "http://i.onionstatic.com/onion/5298/2/16x9/800.jpg",
                url: "http://www.theonion.com/article/hillary-clinton-pleasantly-surprised-after-finding-52593",
                avatar: "http://assets.onionstatic.com/onion/static/images/onion_logo.png"
            },
            {
                title: "GOP Leaders Assure Sobbing Rubio It Not His Fault Party Splitting Up",
                subtitle: "NEWS IN BRIEF",
                date: "March 17 2016",
                volume: "52",
                issue: "10",
                tags: "Politics · Politicians · Election 2016 · Republican · Marco Rubio",
                text: "WASHINGTON—In an effort to comfort the distraught former presidential candidate, top GOP leaders reportedly sat down next to a sobbing Marco Rubio Thursday and assured him that it wasn’t his fault the Republican Party was splitting up. “Marco, trust me, this isn’t about you—we’ve been having problems for years,” said RNC chairman Reince Priebus, who consoled the weeping Florida senator by repeatedly telling him that the party’s breakup had nothing to do with anything he had said or done. ",
                image: "http://i.onionstatic.com/onion/5296/8/16x9/800.jpg",
                url: "http://www.theonion.com/article/gop-leaders-assure-sobbing-rubio-it-not-his-fault--52582",
                avatar: "http://assets.onionstatic.com/onion/static/images/onion_logo.png"
            }
        ];

        return(
            <div className="row">
                <div className="col-xs-8 col-xs-offset-2">
                <h2><small>America's Finest News</small></h2>
                {articles.map( e => <Article item={e} />)}
                </div>
            </div>);
    }
});

module.exports = ArticleManager;
